In [1]:
import numpy as np

In [11]:
# Problem 1
arrayEmpty = np.empty((2,2))
print(arrayEmpty)

[[0. 0.]
 [0. 0.]]


In [12]:
arrayOnes = np.ones((4,2))
print(arrayOnes)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
print(np.full((2,2),5,dtype=float))

[[5. 5.]
 [5. 5.]]


In [20]:
print(np.zeros_like(np.ones((2,2),dtype=int)))

[[0 0]
 [0 0]]


In [22]:
print(np.ones_like(np.zeros((2,2),dtype=int)))

[[1 1]
 [1 1]]


In [23]:
new_list=[1,2,3,4]
print(np.array(new_list))

[1 2 3 4]


In [34]:
# Problem 2
npArange =  np.arange(10,50)
print(npArange)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [35]:
npArangeReshape = np.arange(0,9).reshape(3,3)
print(npArangeReshape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
npIdentity = np.eye(3)
print(npIdentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
npRandom=np.random.random(30)
arrayMean = np.mean(npRandom)
print(npRandom)
print(arrayMean)

[0.91865894 0.20461744 0.74317859 0.52156529 0.48824235 0.98426469
 0.02453526 0.91107143 0.09503988 0.76079174 0.18772406 0.33081649
 0.28693111 0.13808048 0.11295172 0.50827705 0.68626153 0.84879149
 0.130488   0.48983537 0.75181429 0.01670259 0.4589299  0.43338921
 0.54264541 0.56286506 0.60537441 0.88612591 0.59229434 0.36427075]
0.486217825900673


In [46]:
array10_10 = np.random.random((10,10))
arrayMin = np.min(array10_10)
arrayMax = np.max(array10_10)
print(array10_10)
print("Min",arrayMin)
print("Max",arrayMax)

[[0.22508237 0.55629834 0.11937161 0.24110318 0.34327518 0.90072157
  0.84610391 0.22421675 0.22657312 0.49531743]
 [0.72176877 0.60316339 0.92305108 0.29829035 0.09616179 0.9182303
  0.92976851 0.70520347 0.51830296 0.72879987]
 [0.45233631 0.48217742 0.79866214 0.12347414 0.39921713 0.14518601
  0.21916247 0.72780465 0.7023988  0.49127933]
 [0.73139909 0.54511769 0.10468368 0.75011138 0.91222034 0.83817919
  0.32057605 0.97427909 0.33557608 0.36914409]
 [0.4854992  0.34789068 0.38460042 0.80890714 0.15156629 0.52306387
  0.91391661 0.00268552 0.12305897 0.10932846]
 [0.53903665 0.58550592 0.34360627 0.93506894 0.94267548 0.49044056
  0.25494678 0.02543124 0.61648271 0.7328565 ]
 [0.35911029 0.17721043 0.10395587 0.07832752 0.55203448 0.67487112
  0.95537988 0.75690234 0.66936928 0.20836959]
 [0.51734453 0.11354254 0.65091472 0.59827643 0.91015392 0.54517726
  0.32632656 0.74875276 0.09937956 0.04300626]
 [0.626378   0.82490412 0.15675791 0.56591864 0.89560982 0.23253133
  0.78051517 

In [50]:
arrayZero = np.zeros(10)
print(arrayZero)
arrayZero[4]=1
print(arrayZero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [54]:
arr = [1,2,0,0,4,0]
fliparray= np.flip(np.array(arr))
print(fliparray)

[0 4 0 0 2 1]


In [61]:
arr2d=np.zeros((3,3))
print(arr2d)
arr2d[0,:]=1
arr2d[-1,:]=1
arr2d[:,0]=1
arr2d[:,-1]=1
print(arr2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [ ]:
arrayCheckBoard = np.zeros((8,8),dtype=int)
print(arrayCheckBoard)
arrayCheckBoard[1::2,::2]=1
arrayCheckBoard[::2,1::2]=1
print(arrayCheckBoard)

In [71]:
# Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Add\n", x+v)
print("Subtract\n",y-w)
print("Multiply\n",x*5)
print("Square\n",y**2)
print("Dot v.w\n",np.dot(v,w))
print("Dot x.v\n",np.dot(x,v))
print("Dot x.y\n",np.dot(x,y))
print("Concatenate row\n",np.concatenate((x,y), axis=0))
print("Concatenate column\n",np.vstack((v,w)))

Add
 [[10 12]
 [12 15]]
Subtract
 [[-6 -6]
 [-4 -4]]
Multiply
 [[ 5 10]
 [15 25]]
Square
 [[25 36]
 [49 64]]
Dot v.w
 219
Dot x.v
 [29 77]
Dot x.y
 [[19 22]
 [50 58]]
Concatenate row
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate column
 [[ 9 10]
 [11 12]]


In [72]:
# np.concatenate((x, v), axis=0)
# x and v cannot concatenate becaused both have different shape (i.e no matching dimension)

In [79]:
# Problem 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Prove A.A−1 = I
A_inv = np.linalg.inv(A)
print(A @ A_inv)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [78]:
# Prove AB ̸= BA.
print("AB =\n", A @ B)
print("BA =\n", B @ A)

AB =
 [ 16  20 -15]
BA =
 [ 22  15 -16]


In [77]:
# Prove (AB)T = BTAT
print((A@B).T)
print((B.T)@(A.T))

[ 16  20 -15]
[ 16  20 -15]


In [76]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])
X = np.linalg.inv(A) @ B
print(X)


[ 2.  1. -2.]


In [93]:
# X2 = np.linalg.solve(A,B)
# print(X2)


In [82]:
# 4.2
import time

size = 1_000_000
L1 = list(range(size))
L2 = list(range(size))

start = time.time()
Lsum = [L1[i] + L2[i] for i in range(size)]
end = time.time()

print("Python list addition time:", end - start)


Python list addition time: 0.17402911186218262


In [83]:
A = np.arange(size)
B = np.arange(size)

start = time.time()
C = A + B
end = time.time()

print("NumPy addition time:", end - start)


NumPy addition time: 0.009791135787963867


In [84]:
start = time.time()
Lmul = [L1[i] * L2[i] for i in range(size)]
end = time.time()
print("Python list multiply time:", end - start)


Python list multiply time: 0.14141440391540527


In [85]:
start = time.time()
C = A * B
end = time.time()
print("NumPy multiply time:", end - start)


NumPy multiply time: 0.006449460983276367


In [86]:
start = time.time()
dot_list = sum(L1[i] * L2[i] for i in range(size))
end = time.time()
print("Python dot time:", end - start)


Python dot time: 0.1103353500366211


In [87]:
start = time.time()
dot_np = np.dot(A,B)
end = time.time()
print("NumPy dot time:", end - start)


NumPy dot time: 0.003591299057006836


In [88]:
M1 = [[1]*1000 for _ in range(1000)]
M2 = [[1]*1000 for _ in range(1000)]

start = time.time()
Mout = [[sum(a*b for a,b in zip(row,col)) for col in zip(*M2)] for row in M1]
end = time.time()

print("Python matrix multiplication time:", end - start)


Python matrix multiplication time: 84.07746124267578


In [89]:
N1 = np.ones((1000,1000))
N2 = np.ones((1000,1000))

start = time.time()
Nout = N1 @ N2
end = time.time()

print("NumPy matrix multiplication time:", end - start)


NumPy matrix multiplication time: 0.10921168327331543
